### PR TITLE
Added cancel method to PromiseTimer

### PR DESCRIPTION
**Pull request by PhilippCh**
I really found a separate cancel method for running promises useful.

Please check whether you're able to add the changes to the library and especially, if my addition of the Id field to IPromise, IPromise<T> and IPendingPromise is okay. Unfortunately, I wasn't able to compare promises with Object.Equals due to them not having a custom equality comparer, so I had to resort to using the Id field to uniquely identify promises.

### CODE REVIEW

**Comment by RoryDungan** [comment]
Just had a look through your code and it looks really good. Would definitely be a useful feature and it's implemented in a nice way. 

Only issue is that all the rest of our code uses a convention where the opening braces after an `if` statement or a method declaration is on a new line, so if you can update your code to be consistent with that we'll be happy to merge it.

**Comment by PhilippCh** [comment]
Sure, I'll do that right away! When developing, I thought my IDE adapted to your style, so I didn't check again before committing..

**Comment by nah0y** [comment]
Hi,

Maybe I miss something, but you added an Id variable to the promises, but never set those Ids to a unique random value or something like that?

**Comment by RoryDungan** [comment]
The Id already existed (@PhilippCh just added it to the interface), and is supposed to be incremented every time we create a new promise. 

However, I just had a look and realised this only happens for the generic version of Promise and not the non-generic version, so I'm going to fix that so that they both work in the same way.

**Comment by RoryDungan** [comment]
The issue with IDs has now been fixed in version 1.2.2. All promises now have their IDs set in their constructor.

**Comment by PhilippCh** [comment]
Thanks for the feedback! I've updated the pull request with the correct formatting.

**Comment by RoryDungan** [comment]
Huh, looks like since I fixed that bug where not all promises had unique IDs it broke your `when_promise_is_cancelled_by_user_reject_promise` test. I had a look at the code and I think I know what's going on. 
```
            var promise = testObject
                .WaitUntil(timeData => timeData.elapsedTime > 1.0f)
                .Catch(ex => caughtException = ex);

            promise.Done(null, ex => caughtException = ex);

            testObject.Update(1.0f);
            testObject.Cancel(promise);
            testObject.Update(1.0f);
```
First we're creating a promise with a WaitUntil and then cancelling it. However, the promise that is actually being assigned to `var promise = ...` _isn't_ the promise returned by the WaitUntil, it's a new promise returned by the `.Catch`. Essentially this means that when we call `testObject.Cancel(promise)` it doesn't actually cancel the WaitUntil, and the test only worked before because the new promise returned by the Catch shared its ID with the WaitUntil. We can fix this by separating out the WaitUntil and Catch though:
```
var promise = testObject
    .WaitUntil(timeData => timeData.elapsedTime > 1.0f);
promise.Catch(ex => caughtException = ex);
```
I'm happy with everything else though so I'll just edit it and then merge.

**Comment by PhilippCh** [comment]
Thanks a lot for the merge, Rory! One quick question: Is this actually expected behaviour? It seems counterintuitive to me that a promise chain returns a promise that when cancelled doesn't actually cancel the source promise. I could try and rework this a bit further if a more intuitive way of cancelling is preferred.

**Comment by nah0y** [comment]
I agree with Philipp :)
If you cancel a promise, this should cancel the source and everything related, like stopping the entire execution. Or maybe you could add a Cancel and a CancelAll? idk

**Comment by RoryDungan** [comment]
The way the system is designed, all calls to .Then or .Catch will return a new promise, so the one returned by Catch is actually separate to the one returned by WaitUntil. Promises also have no reference to their parent promise so there is no way cancelling one could bubble up and cancel others further up the chain. 

According to the A+ spec, Then _may_ return the same promise as it was called on though (see [section 2.2.7](https://promisesaplus.com/#point-40) and [note 3.3](https://promisesaplus.com/#point-71) in the spec), so potentially this could be fixed. I'm not sure how easy that would be to do in C# though and it would require some pretty big restructuring to the way our system works.

**Pull request merged**
