### PR TITLE
Added Promise<T>.First() to find the first promise that returns a value.

### PR DESCRIPTION
**Pull request by alonsohki**

### CODE REVIEW

**Comment by RoryDungan** [comment]
Looks cool but isn't this the same functionality as [`Promise.Race`](https://github.com/Real-Serious-Games/C-Sharp-Promise#racing-asynchronous-operations)?

**Comment by alonsohki** [comment]
Not exactly. Race() is the first of All(), while First() is the first of Sequence().

**Comment by alonsohki** [comment]
This is how I am using it, which is a good use case:
`            ResolveDNS(server)
                .Then(entry =>
                {
                    var requests = from address in entry.AddressList
                                   select new Func<IPromise<double>>(() => GetNTPTime(address));
                    return Promise<double>.First(requests);
                })`
It takes a list of addresses that a host resolves to, and returns the first one that works (in case one of them doesn't work, times out, or raises any other issue).

**Comment by alonsohki** [comment]
Is there any reason why this isn't being approved?

**Comment by RoryDungan** [comment]
@Borningstar or @kalvinpearce can you take a look at this?

**Pull request merged**
