### PR TITLE
Added "elapsedUpdates" to the TimeData class

### PR DESCRIPTION
**Pull request by MorganMoon**
Based off the conversion in pull request #45. the elapsedUpdates works exactly like elapsedTime, just counts the amount of times Update was called on the promise instead

### CODE REVIEW

**Comment by Edycer** [comment]
I am a bit worried about unexpected behaviour due to the order of the update calls with this functionality. 

The user will have to know exactly when the update on the promise timer is called in sequence of update calls. When it is at the start of the update sequence then everything would function as expected. If however the update of the timer is called last in the sequence and a user sets the promise to resolve after one frame then it would resolve on the same frame that it is added instead of the following frame. Worst case would be if the promise timer is updated in a random point in the sequence and promises initialised before the timer is updated would appear to resolve one frame early.

This could probably be addressed in documentation for the promise timer.

**Comment by RoryDungan** [comment]
@Edycer Do you think that's an issue just with this pull request or with the promise timer in general? The case I can think of for what you described would be if you're trying to wait for 1 frame, but the promise ends up getting resolved in the same frame due to the order of updates. I can see the same thing happening if you're using WaitFor with a time less than the last frame time, or if you're using WaitUntil with a predicate that is already true though. Both those cases could resolve in the same frame or the next frame depending on whether you update the promise timer before or after the rest of your logic.

I think if it's a more general issue with the promise timer then we should probably just merge this because it could be useful and isn't introducing any more confusion then there already is. Let me know if you disagree or think there's an aspect of it I'm missing though.

**Comment by Edycer** [comment]
@RoryDungan Yes it is an existing issue with the promise timer. 

However I think it will be much more likely to to be an issue with the frame count. The user is likely expect accurate frame counts especially for the case of one frame. Where as with time due to varying delta times between and limited fidelity waiting for a time is never exact so being out by one frame is less likely to be an issue.

I agree that it worth including in the library just that the documentation should be updated accordingly. As I mentioned before since the user controls when the update is called. All that really needs to be added is a note mentioning that the promise timer should be updated before any other code that could instantiate promises using the promise timer.

**Comment by RoryDungan** [comment]
That's a good point but I realised there is currently no mention of the PromiseTimer in the documentation. I've created a pull request (#50) with a short section covering the promise timer so we should merge that first before adding the elapsedUpdates functionality and its relevant documentation.

**Comment by RoryDungan** [comment]
Okay I added that. If you can expand on the docs to just mention that TimeData now also contains the number of frames elapsed since the start of the WaitUntil/WaitWhile then I'll merge this 👍

**Comment by RoryDungan** [comment]
Hmm not sure why that build failed but I re-ran it manually and it was fine. Noticed the CI is still using Ubuntu 14.04 so if it keeps being flakey I'll update it to 16.04 anyway

**Pull request merged**
