### PR TITLE
Allow recovery from errors, and make method signatures consistent.

### PR DESCRIPTION
**Pull request by joeatsalot**
I was really happy to find C-Sharp-Promise. After using it for nearly a year, however, I've started to feel that it doesn't quite match the spirit of [promises](https://github.com/promises-aplus/promises-spec) in JavaScript. At the same time, it's been incredibly reliable and useful; it's by far the best promise implementation for C#; and I've developed even more respect for the code's creators and contributors.

I made some small changes to my own copy of the code - mainly just method signatures - to make what I see as a cleaner implementation of promises. (See the [release notes](https://github.com/joeatsalot/C-Sharp-Promise/releases/tag/v2.0.0) for more details.) I'm offering these back as thanks, more to show that I care, than from expecting that other people will like what I like. I won't be offended if you don't accept this pull request, but I'll be pleased to have helped, if you do.

### CODE REVIEW

**Comment by ashleydavis** [comment]
Thanks for your contribution. It's awesome that you have C-Sharp-Promise useful. 

There are quite a few changes here and it's going to take same time to work out if this fits our vision. 

Thanks so much for doing the release notes that really helps us understand what you are trying to achieve.

**Comment by joeatsalot** [comment]
Thanks for looking!

**Comment by RoryDungan** [comment]
Unfortunately this breaks the build and has conflicts with the current master, so we cannot merge it

**Comment by joeatsalot** [comment]
No worries, it's been a long time since it could have been merged. Thanks for all your work, @RoryDungan.

**Pull request closed without merging**
