### PR TITLE
Added "WaitFrames" to PromiseTimer in order to wait a specified amount of update calls

### PR DESCRIPTION
**Pull request by MorganMoon**
Added "WaitFrames" to PromiseTimer in order to wait a specified amount of update calls. Also added unit tests for new addition
(Also added .vs and *.ide to git ignore for visual studio 2017)

### CODE REVIEW

**Comment by MorganMoon** [comment]
The reason I implemented this is because of some odd quirks in Unity when they use Coroutines internally, and will run over 1 frame, or you need to wait a frame to use something again (For example - EventSystem.SetSelectedGameObject). I have just ran into sometimes not wanting to wait for "time" but for a set number of frames. Thanks

**Comment by RoryDungan** [comment]
Hey, thanks for submitting this! I had a chat with the other developers for C-Sharp-Promise and although your code looks good (apart from random values in tests which could cause [flaky tests](https://testing.googleblog.com/2016/05/flaky-tests-at-google-and-how-we.html)), we're reluctant to merge this because it encourages writing frame-rate dependant code. Your use case is sound but features like this could encourage other developers to create code that depends on the framerate being constant, which could lead to bugs when the frame rate is not what is expected.

I think that waiting till the next frame, [end of frame](https://docs.unity3d.com/ScriptReference/WaitForEndOfFrame.html) or [fixed update](https://docs.unity3d.com/ScriptReference/WaitForFixedUpdate.html) would also solve your problem without the risk of introducing timing issues. However, adding support for the latter two of those would require adding a dependency on Unity which we don't want because not all users of the library are using it in Unity. 

That said, we actually already use things like that, as well as methods for wrapping a Unity Coroutine in a promise in our internal code, so perhaps that kind of thing has a place in a separate repo of Unity promise tools.

**Comment by MorganMoon** [comment]
@RoryDungan Hey, I was thinking about this pull request again, and maybe instead of adding a straight up WaitFrames() method, we included the frame count in the TimeData class so people could use WaitUntil() or something themselves, that way it isn't really encouraging frame-rate dependent code. I'll do the pull request ofcourse, if that sounds fine to you.

**Comment by adamsingle** [comment]
I'm actually quite OK with that suggestion. I think it's a neat way of doing it and adds flexibility without compromising the core integrity of the design. A simple change with a simple test. I vote yea.

**Comment by RoryDungan** [comment]
Yeah I think that sounds like a good idea!

**Pull request closed without merging**
