### PR TITLE
Added new example project that shows how to wrap awaitable async tasks in a promise.

### PR DESCRIPTION
**Pull request by GFoley83**
Not all awaitable tasks have a "completed" event (such as `DownloadStringCompleted` when using `WebClient`). The example I've added uses the function `PromiseTask` which wraps a `Promise` inside a task. The function takes one argument `Func<Task<IPromise<T>>> asyncTask` ([see here](https://github.com/GFoley83/C-Sharp-Promise/blob/master/Examples/Example6/Program.cs#L77)) where `T` is the type you need to resolve with. The task resolves or rejects the promise once is has completed. 
This kind of logic should help when you want to use a `Promise` with other async tasks, 
E.g.Entity Framework's `await db.SaveChangesAsync();`, `await (...).ToListAsync();` etc. 
In order to use `Task` and `async/await`, the example project I added uses framework 4.5.

### CODE REVIEW

**Comment by GFoley83** [comment]
I also have a slight variation to the above pull request that's actually closer to a more real-world example usage, especially when dealing with `async/await` tasks in an existing solution:
https://dotnetfiddle.net/zXETw6

Happy to submit this as well / instead.

**Comment by ashleydavis** [comment]
Thanks for your contribution, but I can't allow the upgrade of the C# project to .Net 4.5. 

It would be great if you could just add a new example without changing the core code.

**Comment by GFoley83** [comment]
The core code wasn't touched; the only part of my pull request that uses framework 4.5 is the example project I added, "Example 6". `async/await` is not available in 3.5 so not much I can do there. 

I would at the very least provide a code sample somewhere demoing how to use your promise library with `async/await` tasks. Or even fork my dotnetfiddle above and link to it. Especially given the push towards using `async` operations for Entity Framework transactions, Web API calls etc.

**Comment by GFoley83** [comment]
@ashleydavis  The core code wasn't touched; the only part of my pull request that uses framework 4.5 is the example project I added, "Example 6". `async/await` is not available in 3.5 so not much I can do there. 

I would be really useful to at least provide a code sample somewhere like the readme, demoing how to use your promise library with `async/await` tasks. Or even fork my dotnetfiddle above and link to it. Especially given the push towards using `async` operations with Entity Framework, Web API etc. which a lot developers will be doing these days.

**Comment by ashleydavis** [comment]
If you can add this example without changing the project I'll be more than happy to include it.

The project can't be changed, at RSG we used .Net 3.5 so we can't have the project upgraded. To do so would mean we can't use the library that we created.

**Pull request closed without merging**
